/** Contenu de référence issu des PDF fournis (Guide Points Thérapeutiques, Évaluation Pro, Ventouses). */

export const REFERENCE_ANATOMY = [
  { name: "Shen Men (oreille)", region: "Auriculothérapie", type: "point", description: "Point auriculaire du sommet de la fosse triangulaire. Indications : anxiété, insomnie, douleur.", view: "auriculaire", tags: ["oreille", "stress", "sommeil"] },
  { name: "Point Zéro (oreille)", region: "Auriculothérapie", type: "point", description: "Racine de l'hélix, centre. Homéostasie et équilibre général.", view: "auriculaire", tags: ["oreille", "équilibre"] },
  { name: "Sympathique (oreille)", region: "Auriculothérapie", type: "point", description: "Extrémité du crus inférieur de l'anthélix. Spasme viscéral, stress.", view: "auriculaire", tags: ["oreille", "stress"] },
  { name: "Thalamus (oreille)", region: "Auriculothérapie", type: "point", description: "Centre de la conque cymba. Douleur chronique, analgésie.", view: "auriculaire", tags: ["oreille", "douleur"] },
  { name: "Zone Cervicale (oreille)", region: "Auriculothérapie", type: "point", description: "Anthélix secteur inférieur. Douleur cervicale, céphalée.", view: "auriculaire", tags: ["nuque", "cervical"] },
  { name: "Zone Lombaire (oreille)", region: "Auriculothérapie", type: "point", description: "Anthélix secteur supérieur. Lombalgie, sciatique.", view: "auriculaire", tags: ["lombaires", "dos"] },
  { name: "GV20 Baihui", region: "Visage & tête", type: "point", description: "Couronne du crâme, méridien Vaisseau Gouverneur. Élève le yang, clarifie l'esprit.", view: "antérieure", tags: ["tête", "méridien"] },
  { name: "BL2 Zanzhu", region: "Visage & tête", type: "point", description: "Sourcil médial, méridien Vessie. Yeux, sinus, céphalée.", view: "antérieure", tags: ["yeux", "sinus"] },
  { name: "LI20 Yingxiang", region: "Visage & tête", type: "point", description: "Côté de la narine, Gros Intestin. Sinusite, perte d'olfaction.", view: "antérieure", tags: ["sinus", "nez"] },
  { name: "BL13 Feishu", region: "Dos — Vessie", type: "point", description: "Point Bei Shu T3, poumon. Toux, asthme, affections cutanées.", view: "postérieure", tags: ["dos", "poumon", "BL13"] },
  { name: "BL15 Xinshu", region: "Dos — Vessie", type: "point", description: "Point Bei Shu T5, cœur. Insomnie, anxiété, mémoire.", view: "postérieure", tags: ["dos", "coeur", "BL15"] },
  { name: "BL18 Ganshu", region: "Dos — Vessie", type: "point", description: "Point Bei Shu T9, foie. Yeux, tendons, irritabilité.", view: "postérieure", tags: ["dos", "foie", "BL18"] },
  { name: "BL20 Pishu", region: "Dos — Vessie", type: "point", description: "Point Bei Shu T11, rate. Faiblesse digestive, fatigue.", view: "postérieure", tags: ["dos", "digestion", "BL20"] },
  { name: "BL23 Shenshu", region: "Dos — Vessie", type: "point", description: "Point Bei Shu L2, rein. Lombalgie, fatigue, oreilles.", view: "postérieure", tags: ["lombaires", "rein", "BL23"] },
  { name: "BL25 Dachangshu", region: "Dos — Vessie", type: "point", description: "Point Bei Shu L4, gros intestin. Constipation, SII, lombaire.", view: "postérieure", tags: ["digestion", "lombaires", "BL25"] },
  { name: "BL40 Weizhong", region: "Membres", type: "point", description: "Milieu du pli poplité, Vessie. Dos, genou, récupération.", view: "postérieure", tags: ["genou", "dos", "BL40"] },
  { name: "LI4 Hegu", region: "Membres", type: "point", description: "Espace pouce/index, Gros Intestin. Douleur, immunité, céphalée.", view: "antérieure", tags: ["main", "douleur", "LI4"] },
  { name: "ST36 Zusanli", region: "Membres", type: "point", description: "4 cm sous le genou latéral, Estomac. Fatigue, digestion, immunité.", view: "antérieure", tags: ["jambe", "digestion", "ST36"] },
  { name: "LV3 Taichong", region: "Membres", type: "point", description: "Espace 1er/2e métatarse, Foie. Stress, menstruel, céphalée.", view: "antérieure", tags: ["pied", "stress", "LV3"] },
  { name: "Zone 1 — Dos supérieur & cou", region: "Zones corporelles", type: "zone", description: "Ventouses 4–6 cm, 10–15 min. Douleur cervicale, céphalée, insomnie. Méridiens BL, GB, GV.", view: "postérieure", tags: ["ventouse", "cou", "dos"] },
  { name: "Zone 3 — Lombaire & sacrum", region: "Zones corporelles", type: "zone", description: "Ventouses 6–8 cm, 15–20 min. Lombalgie, sciatique, hanche. Méridiens BL, KD, GV.", view: "postérieure", tags: ["ventouse", "lombaires", "sciatique"] },
  { name: "Zone 4 — Abdomen & thorax", region: "Zones corporelles", type: "zone", description: "Ventouses 4–5 cm, 5–10 min. Digestion, menstruel, anxiété. Méridiens ST, SP, CV.", view: "antérieure", tags: ["ventouse", "abdomen", "digestion"] },
  { name: "Fascia thoraco-lombaire", region: "Dos", type: "fascia", description: "Réseau conjonctif postérieur, repère de lecture du dos en pratique manuelle.", view: "postérieure", tags: ["fascia", "lombaires"] },
  { name: "Trapèze supérieur", region: "Ceinture scapulaire", type: "muscle", description: "Structure entre nuque et épaule, repère fréquent en ventousothérapie du dos supérieur.", view: "postérieure", tags: ["nuque", "épaule", "dos"] },
] as const;

export const REFERENCE_EXERCISES = [
  {
    name: "Ventouses — Dos cervical & nuque",
    category: "recovery",
    objective: "Soulager douleur cervicale et tension du haut du dos.",
    instructions: "Points : BL 10, 11, 12, 13, GB 21, GV 14. Ventouses 4–6 cm, stationnaire 10 min puis glissement le long du méridien de la Vessie. 2×/semaine pendant 4 semaines.",
    durationSeconds: 600,
    repetitions: "2 séances / semaine",
    frequency: "4 semaines puis réévaluation",
    precautions: "Éviter succion directe sur les processus épineux.",
  },
  {
    name: "Ventouses — Lombaire & sciatique",
    category: "recovery",
    objective: "Réduire lombalgie et tension sciatique.",
    instructions: "Points : BL 23, 25, 40 ; GV 4 ; GB 30. Ventouses 6–8 cm, stationnaire 15–20 min, flash cupping sur sacrum si indiqué.",
    durationSeconds: 900,
    repetitions: "2×/sem. phase aiguë",
    frequency: "1×/sem. phase chronique",
    precautions: "Éviter sacrum/lombaire pendant la grossesse.",
  },
  {
    name: "Ventouses — Support respiratoire",
    category: "breathing",
    objective: "Accompagner asthme, toux et tension thoracique.",
    instructions: "Points : BL 13, BL 12, CV 17, LU 1, DU 14. Schéma en éventail sur le dos supérieur, succion légère 10–12 min.",
    durationSeconds: 720,
    repetitions: "3×/sem. en phase aiguë",
    frequency: "1×/sem. en entretien",
    precautions: "Éviter clavicules et colonne vertébrale.",
  },
  {
    name: "Ventouses — Digestion & SII",
    category: "recovery",
    objective: "Soutenir digestion et confort abdominal.",
    instructions: "Points : BL 20, 21, 25 ; ST 25, CV 12 ; ST 36. Glissement abdominal horaire + dorsal stationnaire.",
    durationSeconds: 600,
    repetitions: "1–2× / semaine",
    frequency: "Selon tolérance",
    precautions: "À jeun ou 2 h après repas.",
  },
  {
    name: "Ventouses — Insomnie & stress",
    category: "relaxation",
    objective: "Favoriser sommeil et détente du système nerveux.",
    instructions: "Points : HT7, BL15, KD3, Yintang. Ventouses 3–5 cm, stationnaire légère 10 min. 3×/sem. × 3 semaines.",
    durationSeconds: 600,
    repetitions: "3 séries / semaine",
    frequency: "3 semaines",
    precautions: "Succion douce sur zones sensibles.",
  },
  {
    name: "Ventouses — Anxiété & stress",
    category: "relaxation",
    objective: "Réduire tension nerveuse et hypertonie thoracique.",
    instructions: "Points : PC6, HT7, CV17, GV20. Glissement doux, ventouses 3–5 cm. 2×/sem. × 4 semaines.",
    durationSeconds: 600,
    repetitions: "2× / semaine",
    frequency: "4 semaines",
    precautions: "Adapter l'intensité à la sensibilité cutanée.",
  },
  {
    name: "Ventouses — Céphalées",
    category: "recovery",
    objective: "Soulager céphalées tensionnelles et cervico-céphaliques.",
    instructions: "Points : BL10, GB20, LI4, ST8. Dos supérieur + nuque, ventouses 3–5 cm.",
    durationSeconds: 480,
    repetitions: "Au besoin + prévention",
    frequency: "Selon crise",
    precautions: "Éviter le visage en succion forte.",
  },
  {
    name: "Ventouses faciales — Rajeunissement",
    category: "relaxation",
    objective: "Drainage lymphatique et contour du visage.",
    instructions: "Micro-ventouses < 3 cm. Séquence : décolleté, mâchoire, joues, regard, front. Jamais plus de 3 s en stationnaire sur le visage.",
    durationSeconds: 900,
    repetitions: "1 séance complète",
    frequency: "1× / semaine",
    precautions: "Succion minimale sur peau du visage.",
  },
  {
    name: "Auriculothérapie — Protocole douleur",
    category: "recovery",
    objective: "Moduler la douleur via points auriculaires.",
    instructions: "Identifier points actifs (Shen Men, Thalamus, zone lombaire/cervicale selon plainte). Micro-ventouse ou perle 5–20 min. Documenter les points traités.",
    durationSeconds: 1200,
    repetitions: "1 protocole / séance",
    frequency: "2× / semaine",
    precautions: "Contre-indications oreille infectée ou plaie.",
  },
  {
    name: "Auto-évaluation douleur (0–10)",
    category: "mobility",
    objective: "Mesurer l'évolution de la douleur entre les séances.",
    instructions: "Demander au client de noter son intensité sur 10 avant et après la séance. Consigner localisation, durée et facteurs aggravants/soulageants.",
    durationSeconds: 300,
    repetitions: "À chaque séance",
    frequency: "Systématique",
    precautions: "Documenter dans le dossier client.",
  },
  {
    name: "Évaluation initiale — Screening",
    category: "mobility",
    objective: "Repérer contre-indications avant tout protocole.",
    instructions: "Vérifier : grossesse, anticoagulants, pacemaker, plaies ouvertes, infection cutanée, cancer actif, TVP. Adapter ou reporter le traitement.",
    durationSeconds: 600,
    repetitions: "1ère séance",
    frequency: "Puis mise à jour annuelle",
    precautions: "Demander autorisation médicale si doute.",
  },
  {
    name: "Suivi progrès — 8 séances",
    category: "mobility",
    objective: "Structurer le suivi thérapeutique sur 8 séances.",
    instructions: "Révision à la séance 4 : analyser tendances. Séance 8 : réévaluation complète et nouveau plan. Noter objectifs, résultats et ajustements à chaque séance.",
    durationSeconds: 300,
    repetitions: "8 séances",
    frequency: "Révision aux séances 4 et 8",
    precautions: "Communiquer les progrès au client.",
  },
] as const;

export const PROGRAM_TEMPLATES = [
  {
    name: "Protocole ventouses — Dos & nuque (4 sem.)",
    durationDays: 28,
    objective: "Réduire douleur cervicale et tension du haut du dos.",
    message: "Programme basé sur le Guide des Points Thérapeutiques — réévaluation à 4 semaines.",
    exerciseNames: ["Ventouses — Dos cervical & nuque", "Auto-évaluation douleur (0–10)"],
  },
  {
    name: "Protocole ventouses — Lombaire (6 sem.)",
    durationDays: 42,
    objective: "Soulager lombalgie et améliorer la mobilité.",
    message: "Fréquence adaptée phase aiguë puis entretien.",
    exerciseNames: ["Ventouses — Lombaire & sciatique", "Auto-évaluation douleur (0–10)"],
  },
  {
    name: "Accompagnement stress & sommeil (3 sem.)",
    durationDays: 21,
    objective: "Réduire stress et favoriser le sommeil.",
    message: "Combinaison ventouses légères et points auriculaires si indiqué.",
    exerciseNames: ["Ventouses — Insomnie & stress", "Ventouses — Anxiété & stress"],
  },
  {
    name: "Suivi professionnel — 8 séances",
    durationDays: 56,
    objective: "Documenter et optimiser le protocole sur 8 séances.",
    message: "Révision clinique aux séances 4 et 8 selon le système d'évaluation professionnelle.",
    exerciseNames: ["Suivi progrès — 8 séances", "Évaluation initiale — Screening", "Auto-évaluation douleur (0–10)"],
  },
] as const;
