/**
 * Mapping EXPLICITE des 150 protocoles Formation → zone Campus 3D.
 * Source : titre de chaque fiche (les points secondaires ne gagnent jamais).
 */

import type { AnatomyZoneId } from "@/lib/anatomy-zones";

export type ProtocolAnatomyEntry = {
  zoneId: AnatomyZoneId;
  legend: string;
  organs: string[];
};

export const PROTOCOL_ANATOMY_MAP: Record<number, ProtocolAnatomyEntry> = {
  1: { zoneId: "lombaires", legend: "Douleur lombaire", organs: ["Région lombaire haute","Région lombaire basse","Zone sacrée"] },
  2: { zoneId: "trapeze", legend: "Anxiété et stress", organs: ["Trapèze supérieur","Nuque","Zone interscapulaire"] },
  3: { zoneId: "nuque", legend: "Cervicalgie", organs: ["Base du crâne","Nuque latérale","Trapèze supérieur"] },
  4: { zoneId: "dorsal", legend: "Dorsalgie", organs: ["Zone interscapulaire","Rhomboïdes","Région thoracique moyenne"] },
  5: { zoneId: "sacrum", legend: "Sciatique", organs: ["Région lombaire basse","Zone sacrée","Face latérale hanche"] },
  6: { zoneId: "epaule", legend: "Douleur à l'épaule", organs: ["Deltoïde","Sus-épineux","Sous-épineux"] },
  7: { zoneId: "coude", legend: "Épicondylite", organs: ["Épicondyle latéral","Extenseurs avant-bras","Tiers moyen avant-bras"] },
  8: { zoneId: "avant-bras", legend: "Syndrome du canal carpien", organs: ["Face antérieure poignet","Fléchisseurs avant-bras","Tiers moyen avant-bras"] },
  9: { zoneId: "genou", legend: "Douleur au genou", organs: ["Zone rotulienne","Quadriceps distal","Face latérale genou"] },
  10: { zoneId: "pied", legend: "Récupération entorse de cheville", organs: ["Malléole latérale","Malléole médiale","Mollet inférieur"] },
  11: { zoneId: "pied", legend: "Fasciite plantaire", organs: ["Talon","Voûte plantaire","Avant-pied"] },
  12: { zoneId: "crane", legend: "Céphalée de tension", organs: ["Base du crâne","Tempe","Nuque"] },
  13: { zoneId: "crane", legend: "Migraine", organs: ["Base du crâne","Nuque latérale","Trapèze supérieur"] },
  14: { zoneId: "machoire", legend: "Dysfonction temporo-mandibulaire", organs: ["Muscle masséter","Tempe","Nuque"] },
  15: { zoneId: "dorsal", legend: "Tension posturale et scoliose", organs: ["Côté convexe dorsal","Côté concave dorsal","Région lombaire"] },
  16: { zoneId: "lombaires", legend: "Soutien hernie discale", organs: ["Para-vertébral lombaire droit","Para-vertébral lombaire gauche","Zone sacrée"] },
  17: { zoneId: "dorsal", legend: "Contracture musculaire", organs: ["Point de contracture","Zone adjacente supérieure","Zone adjacente inférieure"] },
  18: { zoneId: "trapeze", legend: "Soutien fibromyalgie", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  19: { zoneId: "dorsal", legend: "Récupération post-fracture", organs: ["Zone péri-fracturaire","Segment proximal","Segment distal"] },
  20: { zoneId: "epaule", legend: "Tendinite de la coiffe des rotateurs", organs: ["Deltoïde","Sus-épineux","Sous-épineux"] },
  21: { zoneId: "trapeze", legend: "Récupération musculaire sportive", organs: ["Trapèze supérieur","Région lombaire","Face postérieure cuisse"] },
  22: { zoneId: "sacrum", legend: "Syndrome du piriforme", organs: ["Face latérale hanche","Zone sacrée","Région lombaire basse"] },
  23: { zoneId: "cuisse", legend: "Syndrome de la bandelette ilio-tibiale", organs: ["Face externe cuisse","Bandelette ilio-tibiale","Face latérale genou"] },
  24: { zoneId: "nuque", legend: "Récupération coup du lapin", organs: ["Nuque latérale","Base du crâne","Trapèze supérieur"] },
  25: { zoneId: "dorsal", legend: "Cyphose posturale", organs: ["Zone interscapulaire","Rhomboïdes","Trapèze moyen"] },
  26: { zoneId: "thorax", legend: "Costochondrite", organs: ["Espace intercostal latéral","Région thoracique postérieure","Zone interscapulaire"] },
  27: { zoneId: "dorsal", legend: "Bursite", organs: ["Zone péri-bursale","Muscle adjacent proximal","Muscle adjacent distal"] },
  28: { zoneId: "pied", legend: "Tendinite d'Achille", organs: ["Tendon d'Achille","Mollet inférieur","Mollet supérieur"] },
  29: { zoneId: "lombaires", legend: "Raideur lombaire chronique", organs: ["Région lombaire haute","Région lombaire basse","Zone sacrée"] },
  30: { zoneId: "nuque", legend: "Vertige cervicogénique", organs: ["Base du crâne","Nuque latérale","Région cervicale moyenne"] },
  31: { zoneId: "dorsal", legend: "Libération des points trigger", organs: ["Point trigger principal","Point trigger secondaire","Zone de douleur référée"] },
  32: { zoneId: "mollet", legend: "Jambes lourdes", organs: ["Mollet","Face postérieure cuisse","Creux poplité"] },
  33: { zoneId: "dorsal", legend: "Drainage lymphatique général", organs: ["Zone axillaire","Région lombaire","Face latérale hanche"] },
  34: { zoneId: "pied", legend: "Œdème des chevilles", organs: ["Malléole latérale","Malléole médiale","Mollet inférieur"] },
  35: { zoneId: "avant-bras", legend: "Mauvaise circulation des mains", organs: ["Face antérieure poignet","Avant-bras","Dos de la main"] },
  36: { zoneId: "mollet", legend: "Varices légères", organs: ["Zone péri-variqueuse","Mollet","Face postérieure cuisse"] },
  37: { zoneId: "mollet", legend: "Récupération circulatoire après vol", organs: ["Mollet","Face postérieure cuisse","Région lombaire"] },
  38: { zoneId: "cuisse", legend: "Cellulite et rétention", organs: ["Face externe cuisse","Face postérieure cuisse","Hanche"] },
  39: { zoneId: "pied", legend: "Mains et pieds froids", organs: ["Voûte plantaire","Cheville","Avant-bras"] },
  40: { zoneId: "trapeze", legend: "Soutien hypertension légère", organs: ["Trapèze supérieur","Nuque","Zone interscapulaire"] },
  41: { zoneId: "dorsal", legend: "Drainage post-opératoire", organs: ["Zone péri-cicatricielle","Zone adjacente supérieure","Zone adjacente inférieure"] },
  42: { zoneId: "crane", legend: "Circulation du cuir chevelu", organs: ["Zone frontale","Zone pariétale","Zone occipitale"] },
  43: { zoneId: "mollet", legend: "Soutien insuffisance veineuse", organs: ["Mollet","Face postérieure cuisse","Creux poplité"] },
  44: { zoneId: "machoire", legend: "Drainage du visage", organs: ["Contour de la mâchoire","Pommette","Zone claviculaire"] },
  45: { zoneId: "mollet", legend: "Récupération circulatoire post-effort", organs: ["Mollet","Face postérieure cuisse","Région lombaire"] },
  46: { zoneId: "abdomen", legend: "Stimulation lymphatique abdominale", organs: ["Zone épigastrique","Zone ombilicale","Flanc droit"] },
  47: { zoneId: "thorax", legend: "Soutien asthme léger", organs: ["Zone interscapulaire","Région thoracique haute","Trapèze supérieur"] },
  48: { zoneId: "thorax", legend: "Bronchite chronique", organs: ["Zone interscapulaire","Région thoracique moyenne","Espace intercostal"] },
  49: { zoneId: "crane", legend: "Congestion nasale", organs: ["Zone claviculaire","Nuque","Trapèze supérieur"] },
  50: { zoneId: "crane", legend: "Soutien sinusite chronique", organs: ["Nuque","Base du crâne","Trapèze supérieur"] },
  51: { zoneId: "thorax", legend: "Amélioration de la capacité respiratoire", organs: ["Espace intercostal latéral","Zone interscapulaire","Région thoracique haute"] },
  52: { zoneId: "thorax", legend: "Récupération post-COVID", organs: ["Zone interscapulaire","Région thoracique haute","Trapèze supérieur"] },
  53: { zoneId: "crane", legend: "Soutien allergies saisonnières", organs: ["Zone claviculaire","Nuque","Zone interscapulaire"] },
  54: { zoneId: "thorax", legend: "Toux persistante", organs: ["Zone interscapulaire","Espace intercostal","Région thoracique haute"] },
  55: { zoneId: "nuque", legend: "Soutien apnée du sommeil", organs: ["Nuque","Base du crâne","Zone claviculaire"] },
  56: { zoneId: "thorax", legend: "Renforcement respiratoire du sportif", organs: ["Espace intercostal latéral","Diaphragme postérieur","Zone interscapulaire"] },
  57: { zoneId: "abdomen", legend: "Digestion lente", organs: ["Zone épigastrique","Zone ombilicale","Flanc droit"] },
  58: { zoneId: "abdomen", legend: "Constipation chronique", organs: ["Côlon ascendant","Côlon transverse","Côlon descendant"] },
  59: { zoneId: "abdomen", legend: "Syndrome du côlon irritable", organs: ["Zone ombilicale","Flanc droit","Flanc gauche"] },
  60: { zoneId: "abdomen", legend: "Ballonnements", organs: ["Zone épigastrique","Zone ombilicale","Flanc droit"] },
  61: { zoneId: "abdomen", legend: "Reflux gastro-œsophagien", organs: ["Zone épigastrique","Diaphragme postérieur","Région thoracique basse"] },
  62: { zoneId: "abdomen", legend: "Soutien hépatique", organs: ["Hypocondre droit","Zone épigastrique","Région dorsale droite"] },
  63: { zoneId: "abdomen", legend: "Nausées chroniques", organs: ["Zone épigastrique","Face antérieure poignet","Région thoracique basse"] },
  64: { zoneId: "abdomen", legend: "Détox digestive", organs: ["Zone épigastrique","Côlon ascendant","Côlon descendant"] },
  65: { zoneId: "abdomen", legend: "Gastrite légère", organs: ["Zone épigastrique","Région dorsale moyenne","Diaphragme postérieur"] },
  66: { zoneId: "abdomen", legend: "Soutien perte de poids", organs: ["Zone abdominale haute","Zone abdominale basse","Flanc droit"] },
  67: { zoneId: "trapeze", legend: "Renforcement immunitaire", organs: ["Zone interscapulaire","Trapèze supérieur","Base du cou"] },
  68: { zoneId: "trapeze", legend: "Fatigue chronique", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  69: { zoneId: "trapeze", legend: "Convalescence après maladie", organs: ["Zone interscapulaire","Trapèze supérieur","Région lombaire"] },
  70: { zoneId: "trapeze", legend: "Prévention saisonnière", organs: ["Zone interscapulaire","Trapèze supérieur","Base du cou"] },
  71: { zoneId: "epaule", legend: "Soutien post-vaccinal", organs: ["Deltoïde","Trapèze supérieur","Zone interscapulaire"] },
  72: { zoneId: "trapeze", legend: "Détox générale", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  73: { zoneId: "nuque", legend: "Amélioration du sommeil", organs: ["Nuque","Trapèze supérieur","Zone interscapulaire"] },
  74: { zoneId: "trapeze", legend: "Augmentation de l'énergie", organs: ["Trapèze supérieur","Zone surrénalienne","Région lombaire"] },
  75: { zoneId: "lombaires", legend: "Récupération post-partum", organs: ["Région lombaire","Zone sacrée","Trapèze supérieur"] },
  76: { zoneId: "trapeze", legend: "Soutien ménopause", organs: ["Nuque","Trapèze supérieur","Zone interscapulaire"] },
  77: { zoneId: "trapeze", legend: "Gestion du stress quotidien", organs: ["Trapèze supérieur","Nuque","Zone interscapulaire"] },
  78: { zoneId: "abdomen", legend: "Soutien digestion lente", organs: ["Zone épigastrique","Zone ombilicale","Flanc droit"] },
  79: { zoneId: "lombaires", legend: "Soulagement lombalgie chronique", organs: ["Région lombaire haute","Région lombaire basse","Zone sacrée"] },
  80: { zoneId: "mollet", legend: "Soutien après un long voyage", organs: ["Région lombaire","Face latérale hanche","Mollet"] },
  81: { zoneId: "machoire", legend: "Soulagement du bruxisme", organs: ["Muscle masséter","Tempe","Nuque"] },
  82: { zoneId: "sacrum", legend: "Soutien syndrome prémenstruel", organs: ["Région lombaire basse","Zone sacrée","Flanc droit"] },
  83: { zoneId: "nuque", legend: "Réduction de l'irritabilité", organs: ["Nuque","Trapèze supérieur","Zone interscapulaire"] },
  84: { zoneId: "trapeze", legend: "Soutien du système immunitaire", organs: ["Zone interscapulaire","Trapèze supérieur","Base du cou"] },
  85: { zoneId: "trapeze", legend: "Gestion du burnout", organs: ["Trapèze supérieur","Zone interscapulaire","Nuque"] },
  86: { zoneId: "sacrum", legend: "Régulation du cycle menstruel", organs: ["Zone ovarienne droite","Zone ovarienne gauche","Région lombaire basse"] },
  87: { zoneId: "sacrum", legend: "Soutien fertilité naturelle", organs: ["Zone pelvienne","Région lombaire basse","Zone sacrée"] },
  88: { zoneId: "dorsal", legend: "Drainage lymphatique axillaire", organs: ["Zone axillaire","Trapèze supérieur","Zone claviculaire"] },
  89: { zoneId: "sacrum", legend: "Douleurs menstruelles", organs: ["Région lombaire basse","Zone sacrée","Zone abdominale basse"] },
  90: { zoneId: "dorsal", legend: "Soutien post-chirurgie légère", organs: ["Zone péri-cicatricielle","Trapèze supérieur","Zone interscapulaire"] },
  91: { zoneId: "trapeze", legend: "Amélioration de la texture de la peau", organs: ["Zone interscapulaire","Trapèze supérieur","Région dorsale haute"] },
  92: { zoneId: "cuisse", legend: "Réduction cellulite légère", organs: ["Face externe cuisse","Face postérieure cuisse","Hanche"] },
  93: { zoneId: "abdomen", legend: "Raffermissement cutané", organs: ["Zone abdominale haute","Zone abdominale basse","Flanc droit"] },
  94: { zoneId: "trapeze", legend: "Soutien grossesse (2e et 3e trimestre)", organs: ["Trapèze supérieur","Zone interscapulaire","Nuque"] },
  95: { zoneId: "abdomen", legend: "Soulagement vergetures récentes", organs: ["Zone abdominale haute","Zone abdominale basse","Flanc droit"] },
  96: { zoneId: "trapeze", legend: "Éclat du teint", organs: ["Nuque","Trapèze supérieur","Zone claviculaire"] },
  97: { zoneId: "machoire", legend: "Soutien contour du visage", organs: ["Sous le menton","Mâchoire","Côté du cou"] },
  98: { zoneId: "dorsal", legend: "Soin des cicatrices anciennes", organs: ["Zone péri-cicatricielle","Zone adjacente supérieure","Zone adjacente inférieure"] },
  99: { zoneId: "dorsal", legend: "Soutien acné dorsale", organs: ["Zone interscapulaire","Trapèze supérieur","Région dorsale basse"] },
  100: { zoneId: "trapeze", legend: "Rituel bien-être complet", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
  101: { zoneId: "mollet", legend: "Récupération post-marathon", organs: ["Mollet","Face postérieure cuisse","Région lombaire"] },
  102: { zoneId: "trapeze", legend: "Soutien avant compétition", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  103: { zoneId: "genou", legend: "Soutien tendinite rotulienne", organs: ["Zone rotulienne","Quadriceps distal","Face latérale genou"] },
  104: { zoneId: "trapeze", legend: "Soutien peau sensible", organs: ["Zone interscapulaire","Trapèze supérieur","Région dorsale haute"] },
  105: { zoneId: "pied", legend: "Soutien fasciite plantaire récurrente", organs: ["Talon","Voûte plantaire","Avant-pied"] },
  106: { zoneId: "trapeze", legend: "Récupération entre entraînements", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  107: { zoneId: "mollet", legend: "Soutien crampe musculaire récurrente", organs: ["Mollet supérieur","Mollet inférieur","Face postérieure cuisse"] },
  108: { zoneId: "pied", legend: "Soutien entorse de cheville légère", organs: ["Malléole latérale","Malléole médiale","Mollet inférieur"] },
  109: { zoneId: "trapeze", legend: "Prévention des blessures sportives", organs: ["Trapèze supérieur","Région lombaire","Face postérieure cuisse"] },
  110: { zoneId: "coude", legend: "Soutien coude du tennisman", organs: ["Épicondyle latéral","Extenseurs avant-bras","Tiers moyen avant-bras"] },
  111: { zoneId: "cuisse", legend: "Soutien syndrome de l'essuie-glace", organs: ["Face externe cuisse","Bandelette ilio-tibiale","Face latérale genou"] },
  112: { zoneId: "mollet", legend: "Soutien périostite tibiale", organs: ["Face antérieure tibia","Tibial antérieur","Mollet"] },
  113: { zoneId: "epaule", legend: "Soutien coiffe des rotateurs", organs: ["Deltoïde","Sus-épineux","Sous-épineux"] },
  114: { zoneId: "lombaires", legend: "Récupération musculaire profonde", organs: ["Région lombaire","Face latérale hanche","Face postérieure cuisse"] },
  115: { zoneId: "hanche", legend: "Soutien douleur du bassin sportive", organs: ["Muscle fessier","Face latérale hanche","Crête iliaque"] },
  116: { zoneId: "trapeze", legend: "Récupération après compétition", organs: ["Trapèze supérieur","Région lombaire","Muscle fessier"] },
  117: { zoneId: "cuisse", legend: "Soutien ischio-jambiers", organs: ["Ischio-jambier proximal","Ischio-jambier moyen","Ischio-jambier distal"] },
  118: { zoneId: "pied", legend: "Soutien tendon d'Achille", organs: ["Tendon d'Achille","Mollet inférieur","Mollet supérieur"] },
  119: { zoneId: "epaule", legend: "Soutien épaule du nageur", organs: ["Deltoïde","Sus-épineux","Zone interscapulaire"] },
  120: { zoneId: "trapeze", legend: "Préparation physique de saison", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  121: { zoneId: "crane", legend: "Soutien névralgie occipitale", organs: ["Base du crâne","Muscles sous-occipitaux","Nuque latérale"] },
  122: { zoneId: "dorsal", legend: "Correction posture assise", organs: ["Trapèze supérieur","Zone interscapulaire","Rhomboïdes"] },
  123: { zoneId: "avant-bras", legend: "Soutien syndrome du canal carpien", organs: ["Face antérieure poignet","Fléchisseurs avant-bras","Tiers moyen avant-bras"] },
  124: { zoneId: "dorsal", legend: "Soutien scoliose légère", organs: ["Côté convexe dorsal","Côté concave dorsal","Région lombaire"] },
  125: { zoneId: "sacrum", legend: "Soutien sciatique chronique", organs: ["Région lombaire basse","Zone sacrée","Face latérale hanche"] },
  126: { zoneId: "pied", legend: "Soutien neuropathie périphérique", organs: ["Mollet","Cheville","Voûte plantaire"] },
  127: { zoneId: "nuque", legend: "Soutien vertiges cervicogéniques", organs: ["Base du crâne","Nuque latérale","Région cervicale moyenne"] },
  128: { zoneId: "thorax", legend: "Soutien névralgie intercostale", organs: ["Espace intercostal latéral","Région thoracique postérieure","Zone interscapulaire"] },
  129: { zoneId: "crane", legend: "Soutien migraine chronique", organs: ["Base du crâne","Nuque latérale","Trapèze supérieur"] },
  130: { zoneId: "trapeze", legend: "Rééquilibrage postural global", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
  131: { zoneId: "trapeze", legend: "Mobilité articulaire du senior", organs: ["Trapèze supérieur","Région lombaire","Face latérale hanche"] },
  132: { zoneId: "genou", legend: "Soutien arthrose du genou", organs: ["Zone rotulienne","Face latérale genou","Face médiale genou"] },
  133: { zoneId: "hanche", legend: "Soutien arthrose de la hanche", organs: ["Face latérale hanche","Muscle fessier","Région lombaire basse"] },
  134: { zoneId: "pied", legend: "Équilibre et prévention des chutes", organs: ["Mollet","Cheville","Face latérale hanche"] },
  135: { zoneId: "trapeze", legend: "Soutien raideur matinale", organs: ["Trapèze supérieur","Zone interscapulaire","Région lombaire"] },
  136: { zoneId: "mollet", legend: "Soutien circulation du senior", organs: ["Mollet","Cheville","Face postérieure cuisse"] },
  137: { zoneId: "epaule", legend: "Soutien mobilité de l'épaule du senior", organs: ["Deltoïde","Sus-épineux","Trapèze supérieur"] },
  138: { zoneId: "trapeze", legend: "Soutien qualité de vie du senior", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
  139: { zoneId: "avant-bras", legend: "Soutien mains arthrosiques", organs: ["Dos de la main","Face antérieure poignet","Avant-bras"] },
  140: { zoneId: "bras", legend: "Récupération après immobilisation", organs: ["Segment immobilisé","Articulation proximale","Articulation distale"] },
  141: { zoneId: "dorsal", legend: "Protocole dos complet", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
  142: { zoneId: "trapeze", legend: "Protocole détente profonde", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
  143: { zoneId: "trapeze", legend: "Protocole sportif complet", organs: ["Trapèze et deltoïde","Région lombaire","Face postérieure cuisse"] },
  144: { zoneId: "trapeze", legend: "Protocole anti-âge global", organs: ["Nuque","Zone claviculaire","Trapèze supérieur"] },
  145: { zoneId: "dorsal", legend: "Protocole détox complet", organs: ["Zone interscapulaire","Région lombaire","Zone épigastrique"] },
  146: { zoneId: "trapeze", legend: "Protocole récupération intensive", organs: ["Trapèze supérieur","Région lombaire","Face postérieure cuisse"] },
  147: { zoneId: "sacrum", legend: "Protocole équilibre hormonal", organs: ["Région lombaire basse","Zone sacrée","Zone surrénalienne"] },
  148: { zoneId: "trapeze", legend: "Protocole bien-être exécutif", organs: ["Nuque","Trapèze supérieur","Zone interscapulaire"] },
  149: { zoneId: "trapeze", legend: "Protocole préventif mensuel", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
  150: { zoneId: "trapeze", legend: "Protocole signature de l'institut", organs: ["Nuque et trapèze","Zone interscapulaire","Région lombaire"] },
};

export function anatomyEntryForProtocol(n: number): ProtocolAnatomyEntry | null {
  return PROTOCOL_ANATOMY_MAP[n] ?? null;
}
